[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.17'

remappings = [
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@tokenysolutions/t-rex/=lib/t-rex/contracts/',
    '@onchain-id/solidity/=lib/onchain-id/contracts/'
]
