[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'node_modules']
solc = '0.8.30'

[fmt]
line_length = 120

[solc]
version = '0.8.30'
optimizer = true
optimizer_runs = 200
via_ir = false

[doc]
include = ['src/**/*.sol']

remappings = [
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@tokenysolutions/t-rex/=lib/t-rex/contracts/',
    '@onchain-id/=lib/onchain-id/contracts/',
    'forge-std/=lib/forge-std/src/',
    'erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/',
    'halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/',
    'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    't-rex/=lib/t-rex/',
    'onchain-id/=lib/onchain-id/'
]
