[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'node_modules']

# Solidity compiler
solc = '0.8.30' 


# Remappings for dependencies
remappings = [
    '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@tokenysolutions/t-rex/=node_modules/@tokenysolutions/t-rex/contracts/'
]

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Metadata settings
bytecode_hash = 'ipfs'

# Extra output
extra_output = ['metadata', 'storageLayout']

# EVM version
evm_version = 'paris'

# Verbosity
verbosity = 2
